export const ApiPaths = {
  auth: {
    register: "/api/v1/register",
    registerConsumer: "/api/v1/register/consumer",
    login: "/api/v1/login",
    logout: "/api/v1/logout",
  },
  cart: {
    add: "/api/v1/addToCart/add",
    list: "/api/v1/addToCart/",
    remove: (productId) => `/api/v1/addToCart/remove/${productId}`,
    update: "/api/v1/addToCart/update",
  },
  order: {
    create: "/api/v1/order/create",
    list: "/api/v1/order/",
    stats: "/api/v1/order/stats",
    recent: "/api/v1/order/recent",
    details: (orderId) => `/api/v1/order/${orderId}`,
    cancel: (orderId) => `/api/v1/order/${orderId}/cancel`,
  },
  payments: {
    initiateCod: "/api/v1/payments/initiate-cod",
    list: "/api/v1/payments/",
    details: (paymentId) => `/api/v1/payments/${paymentId}`,
    status: (paymentId) => `/api/v1/payments/${paymentId}/status`,
  },
  wishlist: {
    add: "/api/v1/wishlist/add",
    list: "/api/v1/wishlist/",
    remove: (wishlistId) => `/api/v1/wishlist/${wishlistId}`,
    checkProduct: (productId) => `/api/v1/wishlist/check/${productId}`,
    clear: "/api/v1/wishlist/",
  },
  products: {
    list: "/api/v1/products/",
    categories: "/api/v1/products/categories",
    details: (productId) => `/api/v1/products/${productId}`,
    byProducer: (producerId) => `/api/v1/products/by-producer/${producerId}`,
  },
  reviews: {
    create: "/api/v1/reviews/create-review",
    byProduct: (productId) => `/api/v1/reviews/get-review/${productId}`,
    byUser: (userName) => `/api/v1/reviews/user-review/${userName}`,
  },
  faq: {
    create: "/api/v1/faq/create",
    list: "/api/v1/faq/",
  },
  producer: {
    profile: "/api/v1/producer/profile",
    profileImage: "/api/v1/producer/profile-image",
    changePassword: "/api/v1/producer/change-password",
    createCategory: "/api/v1/producer/createCategory",
    categories: "/api/v1/producer/get-allcategory",
    createProduct: "/api/v1/producer/add-product",
    products: "/api/v1/producer/products",
    productDetails: (productId) => `/api/v1/producer/products/${productId}`,
    updateProduct: (productId) => `/api/v1/producer/products/${productId}`,
    deleteProduct: (productId) => `/api/v1/producer/products/${productId}`,
    sellingRequests: "/api/v1/producer/selling-requests",
    confirmSelling: (productId) =>
      `/api/v1/producer/confirm-selling/${productId}`,
    notifications: "/api/v1/producer/notifications/",
    unreadNotifications: "/api/v1/producer/notifications/unread-count",
    markNotificationRead: (notificationId) =>
      `/api/v1/producer/notifications/${notificationId}/read`,
    markAllNotificationsRead: "/api/v1/producer/notifications/mark-all-read",
  },
  supersaler: {
    profile: "/api/v1/supersaler/profile",
    updateProfile: "/api/v1/supersaler/profile",
    profileImage: "/api/v1/supersaler/profile-image",
    changePassword: "/api/v1/supersaler/change-password",
    approvedProducts: "/api/v1/supersaler/products/approved",
    sellProduct: (productId) => `/api/v1/supersaler/products/sell/${productId}`,
    createSellPost: "/api/v1/supersaler/sell-post/create",
    bulkPosts: "/api/v1/supersaler/bulk-posts",
    addToCart: "/api/v1/supersaler/add",
    cart: "/api/v1/supersaler/",
    checkoutInit: "/api/v1/supersaler/cart/checkout/init",
    sslSuccess: "/api/v1/supersaler/ssl-success",
    sslFail: "/api/v1/supersaler/ssl-fail",
    sslCancel: "/api/v1/supersaler/ssl-cancel",
    checkoutCod: "/api/v1/supersaler/cart/checkout/cod",
    ordersBuy: "/api/v1/supersaler/orders/buy",
    createProduct: "/api/v1/supersaler/product/create",
    // Backend route name is misleading; controller returns supersaler purchase/order list.
    ownProducts: "/api/v1/supersaler/my-products",
  },
  wholesaler: {
    profile: "/api/v1/wholesaler/profile",
    updateProfile: "/api/v1/wholesaler/profile",
    profileImage: "/api/v1/wholesaler/profile-image",
    changePassword: "/api/v1/wholesaler/change-password",
    approvedProducts: "/api/v1/wholesaler/products/approved",
    sellProduct: (productId) => `/api/v1/wholesaler/products/sell/${productId}`,
    bulkPosts: "/api/v1/wholesaler/bulk-posts",
  },
  consumer: {
    profile: "/api/v1/consumer/profile",
    updateProfile: "/api/v1/consumer/profile",
    profileImage: "/api/v1/consumer/profile-image",
    changePassword: "/api/v1/consumer/change-password",
    retailPosts: "/api/v1/consumer/retail-posts",
  },
  chat: {
    create: "/api/v1/chats/create",
    userChats: "/api/v1/chats/user-chats",
    messages: (chatId) => `/api/v1/chats/messages/${chatId}`,
    sendMessage: "/api/v1/chats/send-message",
    editMessage: (messageId) => `/api/v1/chats/messages/${messageId}/edit`,
    deleteMessage: (messageId) => `/api/v1/chats/messages/${messageId}`,
    addReaction: (messageId) => `/api/v1/chats/messages/${messageId}/reactions`,
    removeReaction: (messageId) =>
      `/api/v1/chats/messages/${messageId}/reactions`,
    closeChat: (chatId) => `/api/v1/chats/${chatId}/close`,
  },
  admin: {
    viewSupersalerProduct: "/api/v1/admin/view-supersaler-product",
    updateStatus: (orderId) => `/api/v1/admin/update-status/${orderId}`,
  },
};
